version: '3.7'

services: 
    pg-admin:
        container_name: pg-admin
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@blog.id
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_SERVER='False'
        volumes:
            - $PWD/db/pgadmin:/var/lib/pgadmin
        ports:
            - "10000:80"
        # networks:
        #     - pgadmin

    db-courses:
        container_name: db-courses
        image: postgres:alpine
        restart: always
        environment:
            - POSTGRES_USER=course-user
            - POSTGRES_PASSWORD=course-pass
            - POSTGRES_DB=course-services
        volumes:
            - $PWD/db/courses:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:10100:5432"
        # networks:
        #     - pgadmin
        
# networks:
#     pgadmin:
#         driver: bridges