version: '3.7'

services: 
    pg-admin:
        container_name: pg-admin
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@blog.id
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_SERVER='False'
        volumes:
            - $PWD/db/pgadmin:/var/lib/pgadmin
        ports:
            - "10000:80"
        # networks:
        #     - pgadmin

    db-courses:
        container_name: db-courses
        image: postgres:alpine
        restart: always
        environment:
            - POSTGRES_USER=course-user
            - POSTGRES_PASSWORD=course-pass
            - POSTGRES_DB=course-services
        volumes:
            - $PWD/db/courses:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:10100:5432"
        # networks:
        #     - pgadmin
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
        - zookeeper
        ports:
        - "29092:29092"
        - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# networks:
#     pgadmin:
#         driver: bridges